apiVersion: v1
kind: Service
metadata:
  name: "nginx-service"
  namespace: "nginx-operator-ns"
  labels:
    app: "nginx"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: "nginx"
